# Generated by Django 4.2.4 on 2024-02-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_customuserv2_projeto_proin'),
    ]

    operations = [
        migrations.AddField(
            model_name='aula',
            name='assistida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aula',
            name='link_da_aula',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='aula',
            name='link_da_gravacao',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='aula',
            name='link_da_inscricao',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aula',
            name='nome_da_aula',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='aula',
            name='palestrante',
            field=models.CharField(max_length=255),
        ),
    ]
