# Generated by Django 4.2.4 on 2024-02-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_relatorio_concluido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('conteudo', models.TextField()),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
