# Generated by Django 4.2.4 on 2024-02-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_turma_customuserv2_turma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turma',
            name='codigo',
            field=models.CharField(max_length=10),
        ),
    ]
