# Generated by Django 4.2.4 on 2024-03-14 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_aula_concluido_por_relatorio_concluido_por'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aula',
            old_name='data_da_aula',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='aula',
            old_name='link_da_aula',
            new_name='link_aula',
        ),
        migrations.RenameField(
            model_name='aula',
            old_name='link_da_gravacao',
            new_name='link_gravacao',
        ),
        migrations.RenameField(
            model_name='aula',
            old_name='link_da_inscricao',
            new_name='link_inscricao',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='assistida',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='concluido_por',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='nome_da_aula',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='concluido',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='concluido_por',
        ),
        migrations.AddField(
            model_name='aula',
            name='nome',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aula',
            name='palestrante',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='MarcaConclusaoRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluido', models.BooleanField(default=False)),
                ('data_conclusao', models.DateTimeField(auto_now_add=True)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.relatorio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MarcaConclusaoAula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluida', models.BooleanField(default=False)),
                ('data_conclusao', models.DateTimeField(auto_now_add=True)),
                ('aula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.aula')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
