# Generated by Django 4.2.4 on 2024-03-20 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_aula_assistida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marcaconclusaorelatorio',
            name='relatorio',
        ),
        migrations.RemoveField(
            model_name='marcaconclusaorelatorio',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='MarcaConclusaoAula',
        ),
        migrations.DeleteModel(
            name='MarcaConclusaoRelatorio',
        ),
    ]
