# Generated by Django 4.2.4 on 2024-03-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_remove_marcaconclusaorelatorio_relatorio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorio',
            name='concluido',
            field=models.BooleanField(default=False),
        ),
    ]
