# Generated by Django 4.2.4 on 2024-03-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_relatorio_concluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserv2',
            name='relatorios_concluidos',
            field=models.ManyToManyField(to='videos.relatorio'),
        ),
    ]
