# Generated by Django 4.2.4 on 2024-03-21 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0015_remove_customuserv2_relatorios_concluidos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatorio',
            name='usuario_concluiu',
        ),
        migrations.AddField(
            model_name='customuserv2',
            name='relatorios_concluidos',
            field=models.ManyToManyField(to='videos.relatorio'),
        ),
        migrations.AddField(
            model_name='relatorio',
            name='concluido_por_todos',
            field=models.BooleanField(default=False),
        ),
    ]
