# Generated by Django 4.2.4 on 2024-03-21 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0016_remove_relatorio_usuario_concluiu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuserv2',
            name='relatorios_concluidos',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='concluido_por_todos',
        ),
        migrations.AddField(
            model_name='relatorio',
            name='usuario_concluiu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
