# Generated by Django 4.2.4 on 2024-03-21 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0017_remove_customuserv2_relatorios_concluidos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concluido', models.BooleanField(default=False)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.relatorio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
