# Generated by Django 4.2.4 on 2024-03-25 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0019_statusrelatorio_criado_em_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusrelatorio',
            name='criado_em',
        ),
    ]
