# Generated by Django 4.2.4 on 2024-03-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0020_remove_statusrelatorio_criado_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusrelatorio',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
