# Generated by Django 4.2.4 on 2024-03-27 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0022_rename_ano_do_relatorio_relatorio_ano_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserv2',
            name='relatorios_concluidos',
            field=models.ManyToManyField(blank=True, related_name='usuarios_concluidos', to='videos.relatorio'),
        ),
        migrations.AddField(
            model_name='customuserv2',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='videos.turma'),
        ),
    ]
