# Generated by Django 4.2.4 on 2024-03-27 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0023_customuserv2_relatorios_concluidos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='nome',
            new_name='Nome_Turma',
        ),
    ]
