# Generated by Django 4.2.4 on 2024-03-27 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0024_rename_nome_turma_nome_turma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='turma',
            old_name='Nome_Turma',
            new_name='nome',
        ),
    ]
