# Generated by Django 4.2.4 on 2024-03-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0026_statusaula'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserv2',
            name='aulas_concluidas',
            field=models.ManyToManyField(blank=True, related_name='usuarios_concluidos', to='videos.aula'),
        ),
    ]
